---
# 不要在此保存密码、Token 或私钥。
hosts:
  - site: chengdu
    vm_id: 100
    name: cd-opnsense
    address: 10.10.10.1
    role: gateway
    status: active

  - site: chengdu
    vm_id: 110
    name: cd-omv
    address: 10.10.10.20
    role: storage
    status: active

  - site: chengdu
    vm_id: 120
    name: cd-k3s-server-01
    address: 10.10.10.70
    role: k3s-server
    startup_order: 3
    status: active

