apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/headlamp/
      chart: headlamp
      targetRevision: 0.44.0
      helm:
        valuesObject:
          config:
            watchPlugins: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          service:
            type: ClusterIP
            port: 80
    - repoURL: ssh://git@github.com/zouzonghua/homelab-gitops.git
      targetRevision: main
      path: kubernetes/clusters/chengdu/applications/headlamp-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
