apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 87.18.1
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          replicas: 1
          admin:
            existingSecret: ""
          service:
            type: ClusterIP
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        prometheus:
          prometheusSpec:
            replicas: 1
            retention: 3d
            resources:
              requests:
                cpu: 200m
                memory: 512Mi
              limits:
                cpu: 1000m
                memory: 1Gi
            additionalScrapeConfigs:
              - job_name: pve
                static_configs:
                  - targets:
                      - 10.10.10.2:9100
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
