apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chengdu-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/zouzonghua/homelab-gitops.git
    targetRevision: main
    path: kubernetes/clusters/chengdu
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
