apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argocd-server
  namespace: argocd
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.cd.home.arpa`)
      services:
        - name: argocd-server
          port: 443
          scheme: https
          serversTransport: argocd-server
  tls: {}
