apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: demo-nginx
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`nginx.cd.home.arpa`)
      services:
        - name: nginx
          port: 80
  tls: {}
